"""
AlertHistory ORM Model
─────────────────────
Stores every security alert generated by the AI engine in Neon PostgreSQL.
"""
from datetime import datetime
from sqlalchemy import Integer, String, Float, Boolean, DateTime, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.database import Base


class AlertHistory(Base):
    __tablename__ = "alert_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    alert_type: Mapped[str] = mapped_column(String(100), nullable=False)   # e.g. "weapon_detected"
    severity: Mapped[str] = mapped_column(String(20), nullable=False)      # "critical" | "high" | "medium"
    title: Mapped[str] = mapped_column(String(200), nullable=False)        # "Armed Person Detected"
    description: Mapped[str] = mapped_column(Text, nullable=False)         # Full description string
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True) # AI confidence 0.0-1.0
    frame_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    screenshot_path: Mapped[str | None] = mapped_column(String(255), nullable=True) # e.g. "uuid.jpg"
    notified: Mapped[bool] = mapped_column(Boolean, default=False)         # True if SMS was sent


